### ISSUE TITLE
Setting up covariates

### ISSUE THREAD

**Issue by alhafidzhamdan** [asoltis/MutEnricher#3]
Hi there,
Congrats on a wonderful package. And thank you for the most comprehensive tutorial! Much appreciated.
I am trying to derive my own set of covariates for hg38.
I have downloaded repliseq data for neural progenitor cells from https://www2.replicationdomain.com/database.php# 
And used this command to generate covariates

```
python ../../utilities/get_region_covariates.py Annotated_promoter_HOMER.bed hg38.fa -i interval_files.txt 
Loading regions...
Loaded 19227 regions from input BED file.
  Divided 19227 regions into 20 region chunks.
```
However nothing seemed to happen for very very long (>1 hour)... so i had to abort

```
cat interval_files.txt 
RT_BG01_NPC_hg38.bedgraph	NPC_RT	

head Annotated_promoter_HOMER.bed
chr1	68091	69191	OR4F5	NM_001005484	ENSG00000186092	ENST00000641515	promoter-TSS	1100
chr1	451578	452678	OR4F3	NM_001005224	ENSG00000230178	ENST00000456475	promoter-TSS	1100
chr1	451578	452678	OR4F29	NM_001005221	ENSG00000284733	ENST00000426406	promoter-TSS	1100
chr1	451578	452678	OR4F16	NM_001005277	ENSG00000284662	ENST00000332831	promoter-TSS	1100
chr1	924731	925831	SAMD11	NM_152486	ENSG00000187634	ENST00000342066	promoter-TSS	1100
chr1	959156	960256	NOC2L	NM_015658	ENSG00000188976	ENST00000327044	promoter-TSS	1100
chr1	959584	960684	KLHL17	NM_198317	ENSG00000187961	ENST00000338591	promoter-TSS	1100
chr1	965482	966582	PLEKHN1	NM_001160184	ENSG00000187583	ENST00000379407	promoter-TSS	1100
chr1	981073	982173	PERM1	NM_001369898	ENSG00000187642	ENST00000433179	promoter-TSS	1100
chr1	999997	1001097	HES4	NM_001142467	ENSG00000188290	ENST00000428771	promoter-TSS	1100

head RT_BG01_NPC_hg38.bedgraph 
chr1	100000747	100000806	0.713487
chr1	100002056	100002115	0.714855
chr1	100003760	100003819	0.716606
chr1	100004249	100004308	0.717102
chr1	100005177	100005236	0.718038
chr1	100006848	100006907	0.719705
chr1	100007434	100007493	0.720284
chr1	100008600	100008659	0.721431
chr1	100009671	100009730	0.722477
chr1	10001056	10001115	1.16089
```

Could you help me troubleshoot this please?
Thank you.
A

**Comment by asoltis** [comment]
Hello and thank you for trying the tool!

The likely issue here is that the files listed in "interval_files.txt" with -i/--interval-files need to be bgzip compressed and tabix-indexed to enable querying of the specific regions. The long run time without exit is likely due to an error being thrown in the internal function that reads these files which is then hung up in the multiprocessing. Please try compressing and indexing the input file. I will also look into including some better error handling for such issues.

**Comment by alhafidzhamdan** [comment]
That works! Thank you! 

My VCF files were annotated by SNPEFF and then PURPLE.
It looks like this:
```
`chr17	7673788	.	G	C	.	PASS	ANN=C|missense_variant|MODERATE|TP53|ENSG00000141510|transcript|ENST00000269305.8|protein_coding|8/11|c.832C>G|p.Pro278Ala|1022/2579|832/1182|278/393||,C|missense_variant|MODERATE|TP53|ENSG00000141510|transcript|ENST00000359597.8|protein_coding|7/9|c.832C>G|p.Pro278Ala|832/1152|832/1032|278/343||,C|missense_variant|MODERATE|TP53|ENSG00000141510|transcript|ENST00000504290.5|protein_coding|4/8|c.436C>G|p.Pro146Ala|714/2331|436/645|146/214||,C|missense_variant|MODERATE|TP53|ENSG00000141510|transcript|ENST00000504937.5|protein_coding|4/7|c.436C>G|p.Pro146Ala|714/2271|436/786|146/261||,C|missense_variant|MODERATE|TP53|ENSG00000141510|transcript|ENST00000510385.5|protein_coding|4/8|c.436C>G|p.Pro146Ala|714/2404|436/630|146/209||,C|missense_variant|MODERATE|TP53|ENSG00000141510|transcript|ENST00000610623.4|protein_coding|4/8|c.355C>G|p.Pro119Ala|714/2331|355/564|119/187||,C|missense_variant|MODERATE|TP53|ENSG00000141510|transcript|ENST00000618944.4|protein_coding|4/8|c.355C>G|p.Pro119Ala|714/2404|355/549|119/182||,C|missense_variant|MODERATE|TP53|ENSG00000141510|transcript|ENST00000619186.4|protein_coding|4/7|c.355C>G|p.Pro119Ala|714/2271|355/705|119/234||,C|missense_variant|MODERATE|TP53|ENSG00000141510|transcript|ENST00000610292.4|protein_coding|7/10|c.715C>G|p.Pro239Ala|1082/2639|715/1065|239/354||,C|missense_variant|MODERATE|TP53|ENSG00000141510|transcript|ENST00000620739.4|protein_coding|8/11|c.715C>G|p.Pro239Ala|1022/2579|715/1065|239/354||,C|missense_variant|MODERATE|TP53|ENSG00000141510|transcript|ENST00000617185.4|protein_coding|8/12|c.832C>G|p.Pro278Ala|1034/2724|832/1026|278/341||,C|missense_variant|MODERATE|TP53|ENSG00000141510|transcript|ENST00000420246.6|protein_coding|8/12|c.832C>G|p.Pro278Ala|965/2653|832/1026|278/341||,C|missense_variant|MODERATE|TP53|ENSG00000141510|transcript|ENST00000455263.6|protein_coding|8/12|c.832C>G|p.Pro278Ala|965/2580|832/1041|278/346||,C|missense_variant|MODERATE|TP53|ENSG00000141510|transcript|ENST00000610538.4|protein_coding|8/12|c.715C>G|p.Pro239Ala|965/2580|715/924|239/307||,C|missense_variant|MODERATE|TP53|ENSG00000141510|transcript|ENST00000622645.4|protein_coding|8/12|c.715C>G|p.Pro239Ala|965/2653|715/909|239/302||,C|missense_variant|MODERATE|TP53|ENSG00000141510|transcript|ENST00000445888.6|protein_coding|8/11|c.832C>G|p.Pro278Ala|968/2506|832/1182|278/393||,C|missense_variant|MODERATE|TP53|ENSG00000141510|transcript|ENST00000619485.4|protein_coding|8/11|c.715C>G|p.Pro239Ala|968/2506|715/1065|239/354||,C|missense_variant|MODERATE|TP53|ENSG00000141510|transcript|ENST00000509690.5|protein_coding|5/6|c.436C>G|p.Pro146Ala|568/729|436/597|146/198||WARNING_TRANSCRIPT_NO_STOP_CODON,C|missense_variant|MODERATE|TP53|ENSG00000141510|transcript|ENST00000615910.4|protein_coding|8/11|c.799C>G|p.Pro267Ala|799/1149|799/1149|267/382||,C|upstream_gene_variant|MODIFIER|TP53|ENSG00000141510|transcript|ENST00000576024.1|protein_coding||c.-203C>G|||||201|WARNING_TRANSCRIPT_NO_START_CODON,C|downstream_gene_variant|MODIFIER|TP53|ENSG00000141510|transcript|ENST00000514944.5|protein_coding||c.*429C>G|||||429|WARNING_TRANSCRIPT_INCOMPLETE,C|downstream_gene_variant|MODIFIER|TP53|ENSG00000141510|transcript|ENST00000574684.1|processed_transcript||n.*466C>G|||||466|,C|downstream_gene_variant|MODIFIER|TP53|ENSG00000141510|transcript|ENST00000505014.5|retained_intron||n.*738C>G|||||738|,C|downstream_gene_variant|MODIFIER|TP53|ENSG00000141510|transcript|ENST00000508793.5|protein_coding||c.*1328C>G|||||1328|WARNING_TRANSCRIPT_INCOMPLETE,C|downstream_gene_variant|MODIFIER|TP53|ENSG00000141510|transcript|ENST00000604348.5|protein_coding||c.*1374C>G|||||1374|WARNING_TRANSCRIPT_NO_STOP_CODON,C|downstream_gene_variant|MODIFIER|TP53|ENSG00000141510|transcript|ENST00000503591.1|protein_coding||c.*1441C>G|||||1441|WARNING_TRANSCRIPT_INCOMPLETE,C|intron_variant|MODIFIER|TP53|ENSG00000141510|transcript|ENST00000413465.6|protein_coding|6/6|c.782+393C>G||||||,C|non_coding_transcript_exon_variant|MODIFIER|TP53|ENSG00000141510|transcript|ENST00000635293.1|nonsense_mediated_decay|8/12|n.715C>G||||||;BIALLELIC;HOTSPOT;PURPLE_AF=1.0270;PURPLE_CN=2.03;PURPLE_GERMLINE=DIPLOID;PURPLE_MACN=8.867e-04;PURPLE_VCN=2.09;REPORTED;REP_C=2;REP_S=G;SEC=TP53,ENST00000269305.8,missense_variant,MISSENSE,c.832C>G,p.Pro278Ala;SEW=TP53,ENST00000269305.8,missense_variant,MISSENSE,1;TNC=GGA	GT:AD:DP	0/1:7,76:83	0/0:85,0:85
`
```
Do you have any suggestions as to how I format the `nonsilent_terms.txt` for the coding analysis?
Also is there a function to do a qqplot btw? 
A

**Comment by asoltis** [comment]
Glad to hear that worked. 

Unfortunately, I don't believe the current code will accurately parse these annotations - these are close to the format of "illumina", but the gene name and effect fields are swapped in their ordering. There are some basic parsing features based on common delimiters (e.g. comma or pipe), but these annotations include both so that code will likely incorrectly parse the field. As you can imagine, it is difficult to anticipate all annotation formats from the various available tools. 

I can perhaps look into adding parsing capabilities for "ANN" format fields. For now, I can suggest two options:

1. Re-annotate these VCFs with ANNOVAR (follow [here](https://github.com/asoltis/MutEnricher/wiki/Annotating-with-ANNOVAR)) and use one of its predefined options (e.g. "annovar-refgene") or the nonsilent terms file to define the effects.

2. Parse the "ANN" field and include new, explicit gene name and effect fields in the VCF INFO lines. From your example, it appears the "ANN" field is a comma-delimited list of pipe-delimited variant effect fields for various transcript models. If you parse these, the gene should be "TP53" and the effect should be "missense_variant"; you could  then create new INFO fields, such as: ANN_GENE=TP53;ANN_EFFECT=missense_variant. Then, in your "nonsilent_terms.txt" file, the "Gene line" would be (tab separated): "Gene ANN_GENE x" and one of the effect lines would be: "Effect ANN_EFFECT missense_variant". For this, you would also have to identify all the nonsilent terms SNPEFF uses (e.g. missense_variant, frameshift_deletion, etc.) and include all these in your input file. 

Ultimately, it seems option (1) is easiest, but option (2) is do-able if you want to stick with these annotations. 

There is currently not a function to produce qq plots.

**Comment by asoltis** [comment]
Hello,

I updated the coding analysis code to now include capabilities for parsing SnpEff VCF annotations (version 1.3.2 overall). You can enable this by setting --anno-type to SnpEff, which will parse the ANN INFO field set by SnpEff (updated [quickstart](https://github.com/asoltis/MutEnricher/wiki/Quickstart-guide#annotating-mutations) and [tutorial](https://github.com/asoltis/MutEnricher/wiki/Tutorial#somatic-mutations-and-annotations) info). Hopefully you will find this new capability useful.

**Comment by alhafidzhamdan** [comment]
Amazing stuff! This worked flawlessly! Thanks! A
